trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'python-hello'

steps:
- task: Docker@2
  displayName: Build an image
  inputs:
    repository: $(imageName)
    command: buildAndPush
    Dockerfile: Dockerfile
    containerRegistry: KrushnaACR
    tags: |
      $(Build.BuildId)
      latest
